version: '3'
services:
  web:
    depends_on:
      - graphite-statsd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    restart: always
    environment:
      HOST: graphite-statsd
      PORT: 8125
  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
  graphite-statsd:
      image: graphiteapp/graphite-statsd
      ports:
        - 2003-2004:2003-2004
        - 2023-2024:2023-2024
        - 8125:8125/udp
        - 8126:8126
        - 8080:80